version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "live"
    default_reviewers:
      - "karelhala"
      - "ryelo"
      - "PanSpagetka"
    allowed_updates:
      - match:
          dependency_name: "@redhat-cloud-services/frontend*"
      - match:
          dependency_name: "@patternfly/*"
          dependency_type: "direct"
